transform:
  target: dev
  outputs:

    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_WAREHOUSE_PATH') }}"
      threads: 4
      settings:
        TimeZone: 'UTC'

    ci:
      type: duckdb
      path: ":memory:"
      threads: 2
      settings:
        TimeZone: 'UTC'
    
    prod:
      type: duckdb
      path: "{{ env_var('DUCKDB_WAREHOUSE_PATH') }}"
      threads: 2
      settings:
        TimeZone: 'UTC'